apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-proxy
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: forward-to-backend
    functionRef:
      name: function-proxy
    input:
      apiVersion: proxy.fn.antrakos.github.io/v1beta1
      kind: ProxyInput
      backend:
        url: function-backend.crossplane-system:9443
        # timeout: 0s  # 0 = inherit Crossplane's function timeout
      payload:
        apiVersion: template.fn.crossplane.io/v1beta1
        kind: Input
        # Add the backend function's expected input fields here
